runtime: python311
service: default

entrypoint: gunicorn -b :$PORT app:app

runtime_config:
  operating_system: ubuntu22


handlers:
  # - url: /static/icons_weiß
  #   static_dir: static/icons_weiß
  # - url: /static/images
  #   static_dir: static/images
  # - url: /static
  #   static_dir: static
  # - url: /templates
  #   static_dir: templates
  - url: /.*
    script: app.app
